import 'package:flutter/material.dart';

part 'strings.dart';

/// Signature for the deferred library loader generated by `deferred as`.
///
/// This is the `loadLibrary` function that Dart generates when you use
/// `import 'package:foo/foo.dart' deferred as foo;`.
typedef LibraryLoader = Future<void> Function();

/// Signature for the widget factory called after the library is loaded.
typedef DeferredWidgetBuilder = Widget Function();

/// Wraps a deferred Dart library so it is loaded on demand instead of being
/// bundled in the initial JavaScript chunk.
///
/// On **Flutter Web**, Dart's `deferred as` keyword splits each import into a
/// separate `.js` file that is only downloaded when first needed. This widget
/// manages that loading lifecycle — showing a placeholder while the chunk
/// downloads and the real widget once it is ready.
///
/// On **native platforms** (Android, iOS, desktop) `loadLibrary()` is a no-op
/// that completes synchronously, so the widget behaves as a transparent wrapper
/// with zero overhead.
///
/// ## Basic usage
///
/// ```dart
/// import 'package:my_app/screens/profile_screen.dart' deferred as profile;
///
/// GoRoute(
///   path: '/profile',
///   builder: (context, state) => DeferredWidget(
///     profile.loadLibrary,
///     () => profile.ProfileScreen(),
///   ),
/// );
/// ```
///
/// ## Preloading
///
/// Call [preload] or [preloadAll] while the user is on a previous screen so
/// the chunk is already cached when they navigate:
///
/// ```dart
/// // Warm up two chunks as soon as the user logs in.
/// DeferredWidget.preloadAll([
///   home.loadLibrary,
///   dashboard.loadLibrary,
/// ]);
/// ```
class DeferredWidget extends StatefulWidget {
  /// Creates a [DeferredWidget].
  ///
  /// - [libraryLoader] — the `loadLibrary` tear-off from the deferred import.
  /// - [createWidget]  — factory called once the library is loaded; must
  ///   reference symbols from the deferred library.
  /// - [placeholder]   — shown while loading; defaults to a centred
  ///   [CircularProgressIndicator].
  /// - [errorBuilder]  — shown on failure; receives the error and a [retry]
  ///   callback. Defaults to a minimal error card.
  /// - [animationDuration] — duration of the cross-fade between placeholder
  ///   and the loaded widget. Set to [Duration.zero] to disable.
  const DeferredWidget(
    this.libraryLoader,
    this.createWidget, {
    super.key,
    this.placeholder,
    this.errorBuilder,
    this.animationDuration = const Duration(milliseconds: 300),
  });

  /// The `loadLibrary` function generated by Dart for the deferred import.
  final LibraryLoader libraryLoader;

  /// Factory that returns the widget to display once the library is ready.
  final DeferredWidgetBuilder createWidget;

  /// Widget shown while the library chunk is downloading.
  ///
  /// Defaults to a centred 24×24 [CircularProgressIndicator].
  final Widget? placeholder;

  /// Builder called when the library fails to load.
  ///
  /// Receives [context], the [error], and a [retry] callback.
  final Widget Function(
    BuildContext context,
    Object error,
    VoidCallback retry,
  )? errorBuilder;

  /// Duration of the [AnimatedSwitcher] cross-fade. Defaults to 300 ms.
  final Duration animationDuration;

  // ---------------------------------------------------------------------------
  // Static cache — shared across all instances.
  // ---------------------------------------------------------------------------

  static final Map<LibraryLoader, Future<void>> _pendingLoads = {};
  static final Set<LibraryLoader> _loadedLibraries = {};

  /// Starts loading [loader] and caches the [Future] so subsequent calls
  /// return the same future without re-downloading.
  ///
  /// Safe to call multiple times with the same loader.
  static Future<void> preload(LibraryLoader loader) {
    _pendingLoads[loader] ??= loader().then((_) {
      _loadedLibraries.add(loader);
    }).catchError((Object error) {
      // Remove the failed entry so subsequent calls (retry) try again.
      _pendingLoads.remove(loader);
      throw error;
    });
    return _pendingLoads[loader]!;
  }

  /// Preloads every loader in [loaders] concurrently.
  ///
  /// Useful for warming up the next screen's chunk while the user is still
  /// on the current screen.
  ///
  /// ```dart
  /// DeferredWidget.preloadAll([
  ///   settingsScreen.loadLibrary,
  ///   profileScreen.loadLibrary,
  /// ]);
  /// ```
  static Future<void> preloadAll(List<LibraryLoader> loaders) {
    return Future.wait(loaders.map(preload));
  }

  /// Returns `true` if [loader] has already been downloaded and is ready.
  ///
  /// Use this to skip showing a loading indicator for already-cached chunks.
  static bool isLoaded(LibraryLoader loader) =>
      _loadedLibraries.contains(loader);

  /// Clears the internal cache of loaded and pending libraries.
  ///
  /// Intended **for testing only** — call in `setUp` / `tearDown` to isolate
  /// test cases that depend on load state.
  @visibleForTesting
  static void reset() {
    _pendingLoads.clear();
    _loadedLibraries.clear();
  }

  @override
  State<DeferredWidget> createState() => _DeferredWidgetState();
}

class _DeferredWidgetState extends State<DeferredWidget> {
  Widget? _loadedChild;
  Object? _error;
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _load();
  }

  @override
  void didUpdateWidget(covariant DeferredWidget oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.libraryLoader != widget.libraryLoader) {
      _load();
    }
  }

  void _load() {
    // Already cached — build synchronously, no flicker.
    if (DeferredWidget.isLoaded(widget.libraryLoader)) {
      setState(() {
        _isLoading = false;
        _error = null;
        _loadedChild = widget.createWidget();
      });
      return;
    }

    setState(() {
      _isLoading = true;
      _error = null;
    });

    DeferredWidget.preload(widget.libraryLoader).then((_) {
      if (mounted) {
        setState(() {
          _isLoading = false;
          _loadedChild = widget.createWidget();
        });
      }
    }).catchError((Object error) {
      if (mounted) {
        setState(() {
          _isLoading = false;
          _error = error;
        });
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    if (_error != null) {
      return widget.errorBuilder?.call(context, _error!, _load) ??
          _DefaultErrorWidget(error: _error!, onRetry: _load);
    }

    return AnimatedSwitcher(
      duration: widget.animationDuration,
      switchInCurve: Curves.easeOut,
      switchOutCurve: Curves.easeIn,
      child: _isLoading
          ? (widget.placeholder ?? const _DefaultLoadingWidget())
          : _loadedChild,
    );
  }
}

// ---------------------------------------------------------------------------
// Default loading widget
// ---------------------------------------------------------------------------

class _DefaultLoadingWidget extends StatelessWidget {
  const _DefaultLoadingWidget();

  @override
  Widget build(BuildContext context) {
    return const Center(
      child: SizedBox(
        width: 24,
        height: 24,
        child: CircularProgressIndicator(strokeWidth: 2),
      ),
    );
  }
}

// ---------------------------------------------------------------------------
// Default error widget
// ---------------------------------------------------------------------------

class _DefaultErrorWidget extends StatelessWidget {
  const _DefaultErrorWidget({required this.error, required this.onRetry});

  final Object error;
  final VoidCallback onRetry;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(24),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(Icons.wifi_off_rounded, size: 48, color: theme.disabledColor),
            const SizedBox(height: 16),
            Text(
              _Strings.failedToLoad,
              style: theme.textTheme.titleMedium,
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 8),
            Text(
              _Strings.checkConnection,
              style: theme.textTheme.bodySmall
                  ?.copyWith(color: theme.hintColor),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 24),
            FilledButton.icon(
              onPressed: onRetry,
              icon: const Icon(Icons.refresh_rounded, size: 18),
              label: const Text(_Strings.retry),
            ),
          ],
        ),
      ),
    );
  }
}
